---
- name: AUTOMATIC BACKUP OF RUNNING CONFIG Project Lab R1
  hosts: R1 
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
  - name: DISPLAYING THE RUNNING-CONFIG
    ios_command:
      commands:
      - show running-config
    register: config

  - name: SAVE OUTPUT TO ./backups/
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "backups/backup_{{ inventory_hostname }}_project.txt"

- name: AUTOMATIC BACKUP OF RUNNING CONFIG Project Lab S1
  hosts: S1 
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
  - name: DISPLAYING THE RUNNING-CONFIG
    ios_command:
      commands:
      - show running-config
    register: config

  - name: SAVE OUTPUT TO ./backups/
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "backups/backup_{{ inventory_hostname }}_project.txt"

- name: AUTOMATIC BACKUP OF RUNNING CONFIG Project Lab S2
  hosts: S2 
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
  - name: DISPLAYING THE RUNNING-CONFIG
    ios_command:
      commands:
      - show running-config
    register: config

  - name: SAVE OUTPUT TO ./backups/
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "backups/backup_{{ inventory_hostname }}_project.txt"